### ISSUE TITLE
ERROR [supervisor.docker] Can't create container from <room_assistant>: 404 Client Error: Not Found ("No such image: mkerix/room-assistant-armhf:2.7.1")

### ISSUE THREAD

**Issue by dabozz88** [mKeRix/hassio-repo#6] opened 2020-05-27 19:01 UTC
Describe the bug
room-assistant on Hass.io not loading

**Comment by mKeRix** [comment] 2020-05-27 19:17
Duplicate of mKeRix/room-assistant#202

**Closed by mKeRix** 2020-05-27 19:17 UTC
